spring:
  application:
    name: sigma-auth

  datasource:
    url: jdbc:mysql://localhost:3306/sigma-auth?characterEncoding=utf8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    hikari:
      username: root
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-lifetime: 86430000

  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml # 配置文件的格式，目前只支持 properties 和 yaml 类型
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 8080